[package]
name = "cosmere_epub_parser"
version = "0.1.0"
edition = "2021"

[dependencies]
epub = "2"
html2text = "0.6"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"

[profile.dev]
debug = 0

[profile.release]
debug = 0