[package]
name = "cosmere_epub_parser"
version = "0.1.0"
edition = "2021"

[dependencies]
epub = "~1.2.4"
html2text = "~0.4.4"
serde = { version = "~1.0.147", features = ["derive"] }
serde_json = "~1.0.88"

[profile.dev]
debug = 0

[profile.release]
debug = 0